### ISSUE TITLE
Base DECAT SDI Map Client

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/decat_geonode#1]
List of plugins to include: 
 * standard ones, except for 3D switcher, home, shapefile upload
Theme:
 * see #2

Subtasks:
 * [x] create a MapStore2 project folder (frontend)
 * [x] configure the application
 * [x] include it in the repo
 * [x] create GeoNode templates and other needed stuff to include the page as a menu item (see #8)
 * [x] include frontend build in the deploy script (#11)

**Comment by cezio** [comment]
as for including frontend, ``decat_geonode/frontend`` would be the path, right? but statics should ideally go to ``static/decat`` dir after building.

**Comment by mbarto** [comment]
that should be possible

**Comment by mbarto** [comment]
Fixed by #13
