### ISSUE TITLE
Archive Alerts

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/decat_geonode#109]
As a EO I would like to have the possibility to "Archive" alerts.

Archived Alerts will disappear from the Alerts list.

There should be a new Layer displaying the Archived Alerts.

The same Filter I selected on the DECAT DSS map applies, either temporal or something else.

**Comment by cezio** [comment]
HazardAlert now has ``archived`` flag and ``archived_at`` timestamp (read-only, popluated when archived flag is set).

``/decat/api/alerts/`` API will return unarchived list by default. Client can set filter with ``archived=True|False`` query string arg.
