### ISSUE TITLE
Data Scopes: Region constraints must bind users to the extent

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/decat_geonode#112]
As a user belonging to one or more Groups with Regions constraints on the Data Scope, I must be forced to the constraint BBOX, i.e. the map should not go outside the constrained BBOX.

**Comment by kappu72** [comment]
I guess It's passible to limite map panning , adding an epic that react on CHANGE_MAP_VIEW action and if the new extent is not within data scope regions bbox it resets map view state to previous
