### ISSUE TITLE
Impact Assessment: Promotion to COP

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/decat_geonode#167]
Promotion of Impact Assessments to COP. Permissions should be correct managed.

**Comment by cezio** [comment]
From call with @kappu72 and @ciasio:
 * frontend needs to have endpoint to list promoted hazard alerts,
 * frontend needs to have filtering above by hazard type, alert level, location,
 * promoted hazard alerts list should be ordered from newest (promoted_at) to oldest,
 * frontend needs to have endpoint to get promoted hazard alert with associated Impact Assessments.

**Comment by ciasio** [comment]
Regarding point 3.
The list of events showed to the Emergency manager must be ordered by COP promotion time:
hazard alert with most recent COP promoted first!

**Comment by kappu72** [comment]
Front end needs:
We already have an endoint that is /decat/api/impact_assessments,
This end point already implements hazard__id and other filters.
1) Client needs to add the promoted one.
2) Clients need the possibility to request hazard alert ordered by impact_assessment promoted_at  but this should requested with a param in the url

**Comment by cezio** [comment]
Ah, ok. So, correct me if i'm wrong here: EM should see Hazard Alerts which have at least one Impact Assessments promoted to COP, right?

**Comment by ciasio** [comment]
Right! and they have to be ordered according to the Impact Assessment promoted_at timestamp, with newer first

**Comment by cezio** [comment]
As for creating IA, you should be able to POST to `/decat/api/impact/assessments/` with fields: 
* `title` (string),
* `geometry` (geojson or wkt)
* `hazard` (id of hazard alert)
* `map` (id of map)

Also, promoting IA is a simple PUT with (or PATCH with partial payload) `promoted` set to `True`.

You can also get list of hazard alerts with IAs promoted to COPs with endpoint `/decat/api/cops/`. Filtering should work in the same way as `alerts` endpoint.

**Comment by kappu72** [comment]
So cops endpoint works exactly as alerts endpoint (same filtering capabilities) but return the results ordered by impact_assessment promoted at value.
The impact_assessment api was already implemented by Alessio, was missing only the possibility to filter impact assessment by promote property. i.e.
http://decat-dev.geo-solutions.it/decat/api/impact_assessments/?promoted=true

**Comment by cezio** [comment]
yes, but it also had several small bugs i've fixed. also, test cases were added for both endpoints.

**Comment by kappu72** [comment]
We need to change permission to the assessment map to allow the emergency-manager to load the map

**Comment by cezio** [comment]
this should work now. Code that was supposed to update permissions (which was looking good for first glimpse), was throwing an exception, which was swallowed by unconfigured logging.
