### ISSUE TITLE
Management of permalinks

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/decat_geonode#178]
Envisage also the possibility of sending an email to connected Resources (whenever available)

**Comment by kappu72** [comment]
I need more detail

**Comment by kappu72** [comment]
We have a problem related to map save permission. When a permalink is passed,  only the emergency manager should be allowed to edit the Cop.

**Comment by afabiani** [comment]
Permalinks will be available only for "global" annotations, linked to "hazard_id" instead of "map_id". See Issue #223

Also the client should call a service in order to ask to the backend for the last available "map_id", i.e. the most recent COP (promoted Impact Assessment).

**Comment by mbarto** [comment]
There are 2 different permalinks:
 * annotations saved in map context: the permalink is to the map / annotation combination
 * annotations saved with CRUD: the permalink is to the hazard (latest COP) / annotation combination
