### ISSUE TITLE
Upload Layer fails

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/decat_geonode#185]
Cannot upload a new layer

Environment: DEV

Steps to reproduce:
 - Log in
 - Navigate to "Data" -> "Upload Layer"
 - Drag the attached file to the drop box
 - Click "Upload files"

Expected result: the files upload completes with "Your layer was successfully uploaded"

Actual result: the file upload completes with the following error
![2017-09-20_1525.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55fc437f80356d12003c764c/125516c66e82c728ace21e0d46bac4cb74cfd3f0c2bbef7cf508a2c16b0a65633b0ba92e7391a172fd172254595f1ffa465a0b10aaaf8c2ba6b23f7283550fead87f4366846c4ff8e7df46f554f832815d84b1b68b49c0ed3424e38a87463f1d070ac4.png)

Test Shapfile:
[points_italy.zip](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55fc437f80356d12003c764c/125516c66e82c728ace21e0d46f89b932d96909686fdbe4fbd1fbcd6395428792c07b7692ac7b671ea142b0009584cf8150e0941fcf98d28a4bf35748d5519f1c32f0e2a92624cf5f2d75dad0ba8218c4584b3bc8f45c1ec3f24e48e8b492c53.zip)

**Comment by afabiani** [comment]
At least in DEV problem seems to be in loca_settings, see below

``` # you can override settings below
 37 DATABASES = {
 38     'default': {
 39          'ENGINE': 'django.contrib.gis.db.backends.postgis',
 40          'NAME': 'geonode',
 41          'USER': 'geonode',
 42          'PASSWORD': 'change_this',
 43          'CONN_TOUT': 900,
 44      },
 45     # vector datastore for uploads
 46     'datastore' : {
 47         'ENGINE': 'django.contrib.gis.db.backends.postgis',
 48         #'ENGINE': '', # Empty ENGINE name disables
 49         'NAME': 'geonode_data',
 50         'USER' : 'geonode',
 51         'PASSWORD' : 'change_this',
 52         'HOST' : 'localhost',
 53         'PORT' : '5432',
 54         'CONN_TOUT': 900,
 55     }
 56 }
 57
 58 GEOSERVER_LOCATION = os.getenv(
 59     'GEOSERVER_LOCATION', 'http://localhost:8080/geoserver/'
 60 )
 61
 62 GEOSERVER_PUBLIC_LOCATION = os.getenv(
 63     'GEOSERVER_PUBLIC_LOCATION', '{}/geoserver/'.format(SITEURL)
 64 )
 65
 66 OGC_SERVER_DEFAULT_USER = os.getenv(
 67     'GEOSERVER_ADMIN_USER', 'admin'
 68 )
 69
 70 OGC_SERVER_DEFAULT_PASSWORD = os.getenv(
 71     'GEOSERVER_ADMIN_PASSWORD', 'change_this'
 72 )
```

**Comment by afabiani** [comment]
After fixing the passwords on loca_settings the issue (at least in DEV) seems to be solved. Please double check.

*pay attention to not alterate local_settings and to not mix them between PROD and DEV*

**Comment by afabiani** [comment]
On PROD GeoFence seems to be broken

**Comment by afabiani** [comment]
Fix PR https://github.com/GeoNode/geonode/pull/3305
