### ISSUE TITLE
Uploads fail in production

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/decat_geonode#192]
Both the layer upload and the model output upload fails in production.

In DEV everything works.

To reproduce:
- Login as IA
- Go to Upload Layer
- Select a shapefile
- Assign permissions as it is not public
- Upload

The upload fails with 
[Errno 111] Connection refused

Also:
- Go to DECAT DSS
- Open an Event
- Open an Assessment
- Add a run that has a Shapefile as an output
- Try to upload a shapefile to the output of the model

The upload fails with "BAD REQUEST"

**Comment by afabiani** [comment]
To be tested again after re-deploy in prod.
