### ISSUE TITLE
Event Manager sees an event entry for every assessment the event has

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/decat_geonode#194]
The Event Manager sees duplicate events, one for each promoted assessment that event has.
![2017-09-26_1817.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55fc437f80356d12003c764c/125516c66e82c728ace21e0d46bac4cb74cfd3f0c2bbe97cf505a1c36b0a65633b0ba92e7391a172fd172254595f1ffa465a0b10aaaf8c2ba6b23f7283550fead87f4366846c4ff8e7df46f554f832815d84bfb68b49c0ee3921e58c884b381d040ac4.png)

**Comment by kappu72** [comment]
That's a backend issue, the endpoint api/decat/cop/ respond with duplicated hazrad.

**Comment by simboss** [comment]
@kappu72 can you liaise with @cezio for fixing this bug?

I think it is critical for this release.

**Comment by cezio** [comment]
fixed
