### ISSUE TITLE
Annotations resources icons

### ISSUE THREAD

**Issue by kappu72** [geosolutions-it/decat_geonode#198]
We need to draw some glyphicons that represents the target resource for instance the icons of police, firefighters, civil protection etc.
We have to integrate this icons with annotation plugin, also reducing the number of   of available colors.

**Comment by ciasio** [comment]
A full legend system need to be designed and implemented  for an effective use of DECAT annotations in COP definition and resources management.
It has to result from associating a selection of markers, pre-defined colors, and glyphs to be edit.

**Comment by simboss** [comment]
@ciasio we would need clear indication of which markers you need in order to have @allyoucanmap start working on this.

**Comment by ciasio** [comment]
3 categories to point out different issues:
   1 - Reference sites from emergency management plan
   2 - Site specific contingencies
   3 - Emergency work forces assignment

1. 
Command & Control HQ
Command & control Local office/unit
Gathering area (area ammassamento mezzi e materiali soccorso)
Evacuation assembly area (area di raduno e attesa della popolazione)
Temporary camp /shelter area
Food and beverages

2.
Site specific incident
Site specific life loss risk
Elderly and dependants

3.
Security
Army
Coast Guard
Fire rescue
Water rescue
Medical rescue

Some suggestion for legging criteria:
To evaluate if to use specific glyphs library for 1st and 3rd cat. and specific library of markers for 2nd cat. E.g. :Assigned annotations regarding site specific contingencies should be marked by 2nd cat related marker and 3rd cat. glyph, changing color of marker according to management status:
- red: to be assigned
- violet: assigned and operating critical
- green: assigned and operating safe
- grey: closed.
The 1cat. may be managed by different glyphs in same-marker/same-color (e.g. regular square shape with white o black background
