### ISSUE TITLE
Layers and data panel

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/decat_geonode#2]
Panel to show a paginated list of data (alerts, hazards, etc.), organized in cards with titles , descriptions, tools, and the TOC in a separated tab (https://github.com/geosolutions-it/decat_geonode/issues/22).

We need to implement:
 - Early warning alerts cards
![image](https://user-images.githubusercontent.com/2770528/27735277-fc2e694a-5d9e-11e7-8368-8f0a804a7bec.png)
 - pagination
![image](https://user-images.githubusercontent.com/2770528/27735291-093d5754-5d9f-11e7-9c18-27eee5fa1409.png)
 - search (on what?)
![image](https://user-images.githubusercontent.com/2770528/27735310-221430f4-5d9f-11e7-81cb-baae27a99272.png)
 - backend interactions to read / filter / paginate data

**Comment by ciasio** [comment]
As time-based pagination is already embedded in the webpage, and filters include region, type and level, I would allow search only by title (free text matching, ordered by updated_at timestamp)
