### ISSUE TITLE
SLD upload unable to extract name

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/decat_geonode#201]
I have a layer in the system that has been uploaded as a model output.

In the Layer managemnt page I choose to upload a style for that layer.

I generate a style with QGIS, give it the same name of the layer and upload it.

The following error occurs: **Please provide a name, unable to extract one from the SLD.

![2017-09-29_1526.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/55fc437f80356d12003c764c/125516c66e82c728ace21e0d46bac4cb74cfd3f0c2bbe67cf508a2c26b0a65633b0ba92e7391a172fd172254595f1ffa465a0b10aaaf8c2ba6b23f7283550fead87f4366846c4ff8e7df46f554f832815d84b1b68b49c0ee3b2ce683894b391e030ac4.png)

**Comment by afabiani** [comment]
Fixed on GeoNode master
