### ISSUE TITLE
Layers disappear on scale denominator 1128 or lower

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/decat_geonode#209]
Add a layer from the catalog to the map.
Zoom to scale 1:1128
The layer is not visible.

The layer is a polygon one, uploaded as a model run output.
There are no scale restrictions in the layer style.

In the browser console I don't see any WMS requests at that zoom level.

**Comment by kappu72** [comment]
I can't reproduce, which one is the layer?

**Comment by kappu72** [comment]
Refere to issue #2252

**Comment by Gnafu** [comment]
Cannot reproduce at the moment
