### ISSUE TITLE
Warning on COP editing

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/decat_geonode#225]
Warning a user that a new Impact Assessment is going to be created. (check on linked maps lock statuses)

**Comment by afabiani** [comment]
when the EM is editing a COP (a map), the client should poll a endpoint like the following one

http://decat-dev.geo-solutions.it/decat/api/cops/<hazard_id>/assessments/

in order to understand if the current COP is still valid or not (i.e. check that the map id is the same)

**Comment by mbarto** [comment]
Apart from notifying the EM, do we need to block any functionality when this happens?
