### ISSUE TITLE
[EM] Emergency Manager should see only the Hazards actually having an available COP

### ISSUE THREAD

**Issue by afabiani** [geosolutions-it/decat_geonode#232]

**Comment by mbarto** [comment]
How do I filter hazards by having available COPS? Should I add a filter to the API request or can I filter client-side on some attribute?

**Comment by mbarto** [comment]
We agreed to:
 * mantain the list of all COPS
 * on click use /decat/api/cops/<id>/assessments/ that returns only the latest COP
 * If empty a warning will be shown and the action canceled

**Comment by afabiani** [comment]
When EM exit the COP all Impact Assessments are shown back again for a certain Alerts.
