### ISSUE TITLE
Data filter widget

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/decat_geonode#3]
Widget to filter data in the data panel (#2) using:
 - generic search
![image](https://user-images.githubusercontent.com/2770528/28056579-a21768b2-661d-11e7-88a0-34fc03254437.png)
 - list of checkboxes to select list of accepted values in specified fields
![image](https://user-images.githubusercontent.com/2770528/27735070-0b54d522-5d9e-11e7-9989-e379b6893785.png)
 - location (multiple configured regions) (#21)
 - time filtering (precooked intervals)
![image](https://user-images.githubusercontent.com/2770528/27735151-68d3cc30-5d9e-11e7-85b2-820adfec2245.png)

**Comment by ciasio** [comment]
About "generic search", see my comment at https://github.com/geosolutions-it/decat_geonode/issues/2
