### ISSUE TITLE
Automatically refresh the Alerts/Hazards list

### ISSUE THREAD

**Issue by Gnafu** [geosolutions-it/decat_geonode#312]
As an Impact Assessor I would like to see new Hazardous Events appear in the hazardous events list without my intervention.

Currently I have to refresh the page or act on the filter to force a refresh of that list.

**Comment by kappu72** [comment]
I guess that we have the same behaviour for  Impact Assessor / alerts,  Event operator / Alerts and Emergency Manager / Cop, isn't it?

**Comment by Gnafu** [comment]
yes
