### ISSUE TITLE
Improvement fixes to alerts filtering

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/decat_geonode#48]
* [x] filtering for levels does not work
 * [x] filtering for regions does not work
 * [x] text search should do a "contains" search (needs support from backend)

**Comment by cezio** [comment]
> ￼ text search should do a "contains" search (needs support from backend)

implemented in https://github.com/geosolutions-it/decat_geonode/commit/0ecffcf3aba4c0e1462c3c17c0d23f87d16e1711

**Comment by mbarto** [comment]
Closed by #51
