### ISSUE TITLE
Early warning - alerts management

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/decat_geonode#5]
We need to be able to insert new alerts, with a form similar to the editing one, with all the fields editable.

**Comment by cezio** [comment]
api reference: https://github.com/geosolutions-it/decat_geonode/wiki/REST-API-Examples#creating-new-alert

**Comment by afabiani** [comment]
Reference mockup form: http://demo.geo-solutions.it/mockups/decat/operator.html
![Schermata 2017-07-11 alle 17.07.19.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/560e3e2385de497500b360f6/125516c66e82c728ace21e0d46db979226908ea89be8ff11f40ca7d979116a227844a2277c80a379e80c2b56415e47be5d4a1f06a3a3dc78e2a436628f550eebd13c0973c46945faee871fbf05b922824681b1b59850d2aa6c7bb3d4d216744b470a83ed5f33aa984fc151f143e44b52ac1b3f67f43b.png)

**Comment by afabiani** [comment]
Regarding "Time" records in this form:
lets skip the manual insert of the time when the event has been noted at first (by the first authority in charge to do that, to monitor that specific sort of hazard, not necessarily included in the organizations registered in DECAT!) as it will be reported on the URI or other documents and it is unnecessary for the DSS work.

The times considered in the form will be (reducing confusion):
- Report Time: when the event is edited in DECAT at the first time, automatic insert by current timestamp
- Update Time: when the event level or description or the region is changed (these attributes in my opinion are the only ones that make sense can change at this level of emergency management), automatic insert by current timestamp.

**Comment by afabiani** [comment]
Regarding the current implementation of the "new event" form:
- Hazard type icon in the selector is too small. Add label in the drop down menu.

- Some label on the form might be cryptic for some user (e.g. URI). If possible, add pop up with definition/description when mouse is on (or text cursor is inside) the text box, to make sure everybody understand the same for: "Type", "Updated time", "Reported time"

-  "Time" should be defined not just date but by time as well (full timestamp).

- Location by point&click doesn't work (I assume it is part of what has to be completed)

- Regions: different region levels have to be uploaded in the system (I assume it is part of what has to be completed). I would consider to start uploading EU-coded Administrative units (NUTS) from level 1 to level 3 (available at http://ec.europa.eu/eurostat/web/gisco/geodata/reference-data/administrative-units-statistical-units/nuts) or something equivalent if already available in Geonode. 

- If it is not too much time-consuming its implementation, I would ask to suggest the regions to the user according to the location selected by point&click

- SAVE button doesn't work (I assume it is part of what has to be completed)
