### ISSUE TITLE
Early warning - Promotion to Hazardous Event Form

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/decat_geonode#6]
Form to show / edit / promote alerts detail info
![image](https://user-images.githubusercontent.com/2770528/27735996-780bcfdc-5da2-11e7-9442-510c9f98329e.png)

**Comment by cezio** [comment]
For the record: in API, you need to update alert to promote. You can do it with ``PATCH`` method, which doesn't require full alert structure, just fields you modify.

```
PATCH /decat/api/alerts/123/

 {'promoted': true}
```
