### ISSUE TITLE
Time saved in server timezone

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/decat_geonode#88]
When we create / save an alert, the timestamps are generated on the server, that runs in a different timezone than the client, so for example if we create an alert at 10.00AM Rome Time, it will be saved as 04.00AM pacific time (or another timezone, depends on server location).
We should generate timestamps on the client.

**Comment by kappu72** [comment]
Why not to set all timestamp in UTC?

**Comment by cezio** [comment]
i'm not sure if different timezone set in server is a right reason to generate timestamps on client side. it's more likely that client's setup have it's clock skewed or set in wrong timezone. I'm reviewing this and set it to CEST where applicable.

**Comment by cezio** [comment]
decat api will return timestamps with tz info (usually with Z tz, which is notation for UTC in iso8601). You should be able to use tz-aware timestamps in filters
