### ISSUE TITLE
Impact Assesment Create / Edit panel

### ISSUE THREAD

**Issue by mbarto** [geosolutions-it/decat_geonode#98]
This new panel will be structured as an accordion with different sections:
 * Ancillary data (still needed? probably replaced by the Catalog, or moved to previous panel)
 * Models (to be detailed)
 * Additional Data (to be detailed)

![image](https://user-images.githubusercontent.com/2770528/28710821-c7ece56a-7385-11e7-8889-6db7bb7c171e.png)

The purpose is to add layers / groups to the TOC and create a map that can be then saved, together with some "metadata" (docs, etc.)

**Comment by tdipisa** [comment]
still needed after the latest mockup review [here](http://demo.geo-solutions.it/mockups/decat/impact-assessment-000-rev.html) ?
